# Bu araç @mebularts tarafından ♥ ile kodlanmıştır.
name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"        # <- Bu satır varken build.yml değişince otomatik tetiklenmez
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

permissions:
  contents: write

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: 'src deposunu al'
        uses: actions/checkout@v4
        with:
          path: src

      - name: 'builds dalını al'
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Eski derlemeleri temizle
        run: rm -f "$GITHUB_WORKSPACE/builds/"*.cs3 || true

      # JDK 17 → SDK → (AGP 8.7.3 Java 17 ister; 11'e dönmüyoruz)
      - name: JDK 17 ayarla
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v2

      # (İsteğe bağlı) wrapper'ı 8.8'e sabitle – repo içinde zaten 8.8 ise bu adım gereksiz
      - name: Gradle wrapper'ı 8.8'e sabitle
        run: |
          cd "$GITHUB_WORKSPACE/src"
          sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.8-bin.zip#' gradle/wrapper/gradle-wrapper.properties

      - name: Eklentileri derle
        run: |
          set -e
          cd "$GITHUB_WORKSPACE/src"
          chmod +x gradlew
          ./gradlew --no-daemon :Dizipal:make makePluginsJson
          # .cs3 dosyalarını topla
          find . -type f -path "*/build/*.cs3" -exec cp -f {} "$GITHUB_WORKSPACE/builds" \; || true
          # plugins.json'u kopyala (root/build altında üretilir)
          if [ -f build/plugins.json ]; then
            cp -f build/plugins.json "$GITHUB_WORKSPACE/builds/plugins.json"
          elif [ -f app/build/plugins.json ]; then
            cp -f app/build/plugins.json "$GITHUB_WORKSPACE/builds/plugins.json"
          else
            echo "plugins.json bulunamadı!" >&2
            exit 1
          fi

      - name: Derlemeleri yükle (builds dalına)
        run: |
          cd "$GITHUB_WORKSPACE/builds"
          git config --local user.email "actions@github.com"
          git config --local user.name  "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
