# Bu araç @mebularts tarafından ♥ ile kodlanmıştır.
name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Eski Derlemeleri Temizle
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

# JDK 17 → SDK → (JDK 17 kalacak, AGP 8.7.3 bunu istiyor)
- name: JDK 17 Ayarla
  uses: actions/setup-java@v4
  with:
    distribution: temurin
    java-version: '17'

- name: Android SDK Ayarla
  uses: android-actions/setup-android@v3

# (İsteğe bağlı) wrapper'ı 8.8'e sabitle – repo içinde güncellediysek gerek yok
- name: Gradle wrapper'ı 8.8'e sabitle
  run: |
    cd $GITHUB_WORKSPACE/src
    sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.8-bin.zip#' gradle/wrapper/gradle-wrapper.properties

- name: Eklentileri Derle
  run: |
    cd $GITHUB_WORKSPACE/src
    chmod +x gradlew
    ./gradlew --no-daemon :DiziPal:make makePluginsJson
    cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
    cp build/plugins.json $GITHUB_WORKSPACE/builds




      - name: Derlemeleri Yükle
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "$GITHUB_SHA 'nın Derlenmesi" || exit 0   # eğer commit edilecek bir şey yoksa hata verme
          git push --force
